/**
 * The planner. Given one snapshot of what somebody owns and one set of standing
 * instructions, it produces the list of steps to take. It is a pure function: no clock, no
 * network, no randomness, no model. The same snapshot and the same instructions always
 * produce exactly the same plan, which is what makes it possible to test it and to replay
 * it against history.
 *
 * A model never decides any of this. That is rule one of the repo, and it is not a style
 * preference: a sentence generated by a model cannot be replayed, cannot be tested against
 * last month's prices, and takes tens of seconds to arrive.
 *
 * ## The order the steps come out in
 *
 * Sorted, always, and by a key that does not depend on the order the caller happened to
 * pass its holdings in. Two callers with the same holdings in a different order must get
 * byte for byte the same plan, otherwise a plan cannot be compared against a stored one
 * and the "did we already do this" check further down the chain becomes unreliable.
 *
 * ## What is NOT decided here
 *
 * How much of the plan actually gets sent. The planner says what would be right; the
 * limits in `execute.ts` say what is allowed. Keeping those apart is what lets the limits
 * be the last word.
 */
import {
  assertVenueUsable,
  type VenueCapability,
} from "./venues.js";
import {
  BPS_ONE,
  PolicyError,
  RATIO_ONE,
  safetyRatio,
  type PilotPlan,
  type PilotPolicy,
  type PlannedAction,
  type PortfolioSnapshot,
} from "./types.js";

/** Absolute value for bigints. */
function abs(value: bigint): bigint {
  return value < 0n ? -value : value;
}

/**
 * Checks the owner's instructions before a single number is computed from them.
 *
 * Weights that do not add up to 10000 are the dangerous case: they look harmless and they
 * silently change every drift figure, so a mix that is actually correct reads as far off
 * and Pilot trades for no reason. Refused rather than normalised, because normalising
 * would hide a mistake in the instructions somebody wrote by hand.
 */
export function assertPolicyIsSane(policy: PilotPolicy): void {
  if (policy.targets.length === 0) {
    throw new PolicyError("The instructions name no holdings to aim for, so there is nothing to plan.");
  }
  const seen = new Set<string>();
  let total = 0n;
  for (const target of policy.targets) {
    if (seen.has(target.assetId)) {
      throw new PolicyError(
        `The instructions name "${target.assetId}" twice. Which of the two shares applies ` +
          "cannot be guessed, so nothing is planned.",
      );
    }
    seen.add(target.assetId);
    if (target.weightBps < 0n) {
      throw new PolicyError(
        `The share asked for "${target.assetId}" is ${target.weightBps}, which is below zero.`,
      );
    }
    total += target.weightBps;
  }
  if (total !== BPS_ONE) {
    throw new PolicyError(
      `The shares asked for add up to ${total} out of ${BPS_ONE}. They have to add up to ` +
        `exactly ${BPS_ONE}, otherwise every gap this agent measures is wrong and it would ` +
        "trade for no reason.",
    );
  }
  if (policy.driftToleranceBps <= 0n) {
    throw new PolicyError(
      `The allowed drift is ${policy.driftToleranceBps}. With no allowance at all the agent ` +
        "would trade on every rounding step and pay a fee each time.",
    );
  }
  if (policy.idleFloorUsd8 < 0n) {
    throw new PolicyError(`The amount to keep aside is ${policy.idleFloorUsd8}, which is below zero.`);
  }
  if (policy.minSafetyRatio < RATIO_ONE) {
    throw new PolicyError(
      `The lowest safety ratio allowed is ${policy.minSafetyRatio}, which is under 1.0. ` +
        "Below 1.0 the lender is already entitled to sell the holdings, so borrowing down " +
        "to there is never allowed.",
    );
  }
  if (policy.copyFactorBps < 0n || policy.copyFactorBps > BPS_ONE) {
    throw new PolicyError(
      `The share of somebody else's trade to copy is ${policy.copyFactorBps}, which is outside ` +
        `0 to ${BPS_ONE}. Copying more than all of it is not a thing this agent does.`,
    );
  }
  if (policy.maxCopyUsd8 < 0n) {
    throw new PolicyError(`The copy limit is ${policy.maxCopyUsd8}, which is below zero.`);
  }
}

/** The total value of everything held, used as the base for every share calculation. */
export function totalHeldUsd8(snapshot: PortfolioSnapshot): bigint {
  let total = 0n;
  for (const holding of snapshot.holdings) {
    if (holding.valueUsd8 < 0n) {
      throw new PolicyError(
        `Holding "${holding.assetId}" is worth ${holding.valueUsd8}, which is below zero. ` +
          "A reading like that is broken, and planning against it would move real money.",
      );
    }
    total += holding.valueUsd8;
  }
  return total;
}

/**
 * The most that can be borrowed while keeping the loan at or above the safety ratio the
 * owner asked for. Returns zero when the loan is already at or past that line, never a
 * negative number.
 *
 * The whole calculation is in whole numbers and rounds down, so the answer is always at
 * most what is truly allowed and never a hair over it.
 */
export function borrowHeadroomUsd8(
  collateralUsd8: bigint,
  debtUsd8: bigint,
  liquidationThresholdBps: bigint,
  minSafetyRatio: bigint,
): bigint {
  if (minSafetyRatio <= 0n) {
    throw new PolicyError("The lowest safety ratio allowed cannot be zero or below.");
  }
  const maxDebt =
    (collateralUsd8 * liquidationThresholdBps * RATIO_ONE) / (BPS_ONE * minSafetyRatio);
  const headroom = maxDebt - debtUsd8;
  return headroom > 0n ? headroom : 0n;
}

/**
 * Builds the plan.
 *
 * Every step is created through `assertVenueUsable`, so a step naming a place that does not
 * answer on this network cannot get into a plan at all. That check throws rather than
 * skipping quietly: a plan with a step silently dropped looks complete and is not, and the
 * caller would act on it believing the whole job was covered.
 */
export function plan(snapshot: PortfolioSnapshot, policy: PilotPolicy): PilotPlan {
  assertPolicyIsSane(policy);

  const total = totalHeldUsd8(snapshot);
  const actions: PlannedAction[] = [];
  const notes: string[] = [];

  // 1. Bring the mix back to what the owner asked for.
  if (total > 0n) {
    const held = new Map<string, bigint>();
    for (const holding of snapshot.holdings) {
      held.set(holding.assetId, (held.get(holding.assetId) ?? 0n) + holding.valueUsd8);
    }
    const rebalance: PlannedAction[] = [];
    for (const target of policy.targets) {
      const actual = held.get(target.assetId) ?? 0n;
      const wanted = (total * target.weightBps) / BPS_ONE;
      const gap = wanted - actual;
      const actualBps = (actual * BPS_ONE) / total;
      const driftBps = abs(actualBps - target.weightBps);
      if (driftBps < policy.driftToleranceBps) continue;
      if (gap === 0n) continue;
      assertVenueUsable(policy.swapVenueId, "swap");
      rebalance.push({
        kind: "REBALANCE",
        venueId: policy.swapVenueId,
        assetId: target.assetId,
        amountUsd8: abs(gap),
        direction: gap > 0n ? "IN" : "OUT",
        reason:
          `${target.assetId} is ${actualBps} out of ${BPS_ONE} of the total and was asked to be ` +
          `${target.weightBps}. That gap of ${driftBps} is past the ${policy.driftToleranceBps} ` +
          "that is allowed to pass without acting.",
      });
    }
    // Sorted by name so the plan does not depend on the order holdings arrived in.
    rebalance.sort((a, b) => (a.assetId < b.assetId ? -1 : a.assetId > b.assetId ? 1 : 0));
    actions.push(...rebalance);
    if (rebalance.length === 0) {
      notes.push("The mix is within the allowed drift, so nothing is traded.");
    }
  } else {
    notes.push("Nothing is held, so there is no mix to correct.");
  }

  // 2. Put idle money to work, but only what is above the amount kept aside on purpose.
  const deployable = snapshot.idleUsd8 - policy.idleFloorUsd8;
  if (deployable > 0n) {
    assertVenueUsable(policy.stakeVenueId, "stake");
    actions.push({
      kind: "STAKE",
      venueId: policy.stakeVenueId,
      assetId: "BNB",
      amountUsd8: deployable,
      direction: "OUT",
      reason:
        `${snapshot.idleUsd8} is sitting still and ${policy.idleFloorUsd8} is kept aside on ` +
        `purpose, so ${deployable} can earn instead of waiting.`,
    });
  } else {
    notes.push("Nothing is sitting still beyond what is kept aside on purpose.");
  }

  // 3. Mirror somebody else's trade, scaled down and capped.
  const leader = snapshot.leaderTrade;
  if (leader !== undefined && leader.valueUsd8 > 0n && policy.copyFactorBps > 0n) {
    let amount = (leader.valueUsd8 * policy.copyFactorBps) / BPS_ONE;
    let capped = false;
    if (amount > policy.maxCopyUsd8) {
      amount = policy.maxCopyUsd8;
      capped = true;
    }
    if (amount > 0n) {
      assertVenueUsable(policy.swapVenueId, "swap");
      actions.push({
        kind: "COPY_TRADE",
        venueId: policy.swapVenueId,
        assetId: leader.assetId,
        amountUsd8: amount,
        direction: leader.side === "BUY" ? "IN" : "OUT",
        reason:
          `Somebody being followed moved ${leader.valueUsd8} of ${leader.assetId}. ` +
          `${policy.copyFactorBps} out of ${BPS_ONE} of that is ${amount}` +
          (capped ? `, held down to the ${policy.maxCopyUsd8} limit for one copy.` : "."),
      });
    }
  }

  // 4. Borrowing room, reported only. Pilot never borrows on its own initiative here: the
  // room is what the owner is told about, and a borrow step is only produced when the
  // instructions ask for one, which they currently never do.
  const ratio = safetyRatio(
    snapshot.collateralUsd8,
    snapshot.debtUsd8,
    snapshot.liquidationThresholdBps,
  );
  const headroom = borrowHeadroomUsd8(
    snapshot.collateralUsd8,
    snapshot.debtUsd8,
    snapshot.liquidationThresholdBps,
    policy.minSafetyRatio,
  );
  if (snapshot.collateralUsd8 > 0n) {
    notes.push(
      ratio === null
        ? `Nothing is owed. There is room to borrow ${headroom} and stay above the ` +
          `${policy.minSafetyRatio} safety ratio asked for.`
        : `The loan sits at a safety ratio of ${ratio}. There is room to borrow ${headroom} ` +
          `and stay above the ${policy.minSafetyRatio} asked for.`,
    );
  }

  let planTotal = 0n;
  for (const action of actions) planTotal += action.amountUsd8;

  return {
    actions,
    totalUsd8: planTotal,
    reason:
      actions.length === 0
        ? notes.join(" ") || "There is nothing to do."
        : `${actions.length} step${actions.length === 1 ? "" : "s"} worth ${planTotal} in total.`,
  };
}

/**
 * A borrow step, produced only when the owner explicitly asks for one and only for an
 * amount that keeps the loan above the safety ratio they set. Kept apart from `plan` on
 * purpose: taking on debt is the one thing this agent will not start by itself.
 */
export function planBorrow(
  snapshot: PortfolioSnapshot,
  policy: PilotPolicy,
  requestedUsd8: bigint,
): PilotPlan {
  assertPolicyIsSane(policy);
  if (requestedUsd8 <= 0n) {
    return { actions: [], totalUsd8: 0n, reason: "Nothing was asked for." };
  }
  const capability: VenueCapability = "borrow";
  assertVenueUsable(policy.lendVenueId, capability);
  const headroom = borrowHeadroomUsd8(
    snapshot.collateralUsd8,
    snapshot.debtUsd8,
    snapshot.liquidationThresholdBps,
    policy.minSafetyRatio,
  );
  if (headroom <= 0n) {
    return {
      actions: [],
      totalUsd8: 0n,
      reason:
        "The loan is already as large as the safety ratio you set allows, so nothing more " +
        "is borrowed.",
    };
  }
  const amount = requestedUsd8 > headroom ? headroom : requestedUsd8;
  return {
    actions: [
      {
        kind: "BORROW",
        venueId: policy.lendVenueId,
        assetId: "USDT",
        amountUsd8: amount,
        direction: "IN",
        reason:
          amount < requestedUsd8
            ? `You asked for ${requestedUsd8}. Only ${amount} keeps the loan above the ` +
              `${policy.minSafetyRatio} safety ratio you set, so that is what is borrowed.`
            : `${amount} borrowed, which keeps the loan above the ${policy.minSafetyRatio} ` +
              "safety ratio you set.",
      },
    ],
    totalUsd8: amount,
    reason: `One step worth ${amount}.`,
  };
}
